
const USE_LOCAL_STORAGE = false;

const PUBLIC_SERVERS = false;
const HIDE_PUBLIC_SERVERS_TAB = true;
const POST_RENDER_TIMEOUT_MS = 15;

export {
    USE_LOCAL_STORAGE,
    PUBLIC_SERVERS,
    HIDE_PUBLIC_SERVERS_TAB,
    POST_RENDER_TIMEOUT_MS
}