import Color from "parsegraph-color";

const USE_LOCAL_STORAGE = false;

const PUBLIC_SERVERS = false;
const HIDE_PUBLIC_SERVERS_TAB = true;
const POST_RENDER_TIMEOUT_MS = 15;
const LABEL_IS_VISIBLE_SCALE = 0.8;
const TEXT_IS_VISIBLE_SCALE = 0.2;
const DEFAULT_NODE_STYLE = {
  backgroundColor: new Color(0.5, 1, 0.5, 0.1),
  borderColor: new Color(0, 0, 0, 0.5),
  textColor: new Color(0, 0, 0, 1),
  lineColor: new Color(0.9, 0.9, 0.9, 0.8),
};
const SHOW_KEY_STROKES = false;
const PAGE_BACKGROUND_COLOR = new Color(0.2, 0.2, 0.9, 1);
const PRINT_PAINT_STATS = false;
const ENABLE_EXTENT_VIEWING = true;

const CREASE_ROUNDS = 8;

const MAX_ROUNDS = 14;

const MAX_RENDER_ATTEMPTS = 10000;

const SINGLE_TAP_GESTURES = false;

const nodeHasValue = (node) =>
  typeof node.value() === "string" || typeof node.value() === "number";

const FONT_SIZE = 10;
const WORLD_LABEL_SIZE = 15;
const FONT_UPSCALE = 8;
const LINE_HEIGHT = FONT_SIZE;
const BORDER_THICKNESS = FONT_SIZE/10;
const LINE_THICKNESS = (FONT_SIZE/10)*3;
const BORDER_ROUNDEDNESS = (FONT_SIZE/10)*5;
const MAX_CLICK_DELAY_MS = 1000;
const MOVE_SPEED = FONT_SIZE;
const BUD_SIZE = 0.75;
const NODE_SEPARATION = FONT_SIZE/2;
const INWARD_SEPARATION = 2*BORDER_ROUNDEDNESS;
const LINE_SPACING = 2;
const MAX_PAINT_TIME_MS = 1000 / 60 * .9;

const CRANK_SPEED_MS = 500;
const SLOW_RENDER = false;

const DONT_TOUCH_CAMERA = true;

const SHOW_WORLD_LABELS = true;
const SHOW_NODE_SPOTLIGHTS = true;

export {
  LINE_SPACING,
  WORLD_LABEL_SIZE,
  NODE_SEPARATION,
  SHOW_NODE_SPOTLIGHTS,
  DONT_TOUCH_CAMERA,
  SHOW_WORLD_LABELS,
  SLOW_RENDER,
  SINGLE_TAP_GESTURES,
  MAX_RENDER_ATTEMPTS,
  CRANK_SPEED_MS,
  MAX_PAINT_TIME_MS,
  FONT_SIZE,
  FONT_UPSCALE,
  LINE_HEIGHT,
  LINE_THICKNESS,
  BORDER_ROUNDEDNESS,
  BORDER_THICKNESS,
  MOVE_SPEED,
  BUD_SIZE,
  INWARD_SEPARATION,
  MAX_CLICK_DELAY_MS,
  nodeHasValue,
  MAX_ROUNDS,
  ENABLE_EXTENT_VIEWING,
  PRINT_PAINT_STATS,
  CREASE_ROUNDS,
  PAGE_BACKGROUND_COLOR,
  SHOW_KEY_STROKES,
  DEFAULT_NODE_STYLE,
  USE_LOCAL_STORAGE,
  PUBLIC_SERVERS,
  HIDE_PUBLIC_SERVERS_TAB,
  TEXT_IS_VISIBLE_SCALE,
  LABEL_IS_VISIBLE_SCALE,
  POST_RENDER_TIMEOUT_MS,
};
