# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Electron app

on:
  push:
    branches: electron

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: ls -R
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 20
        registry-url: 'https://registry.npmjs.org'
    - run: cd occluder && yarn && ./deploy.sh && cd ..
    - run: yarn
    - run: yarn build
    - run: cd build && sed -i -re 's/React App/parsegraph/g' ./index.html
    - run: yarn make
