# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Electron app for Windows

on:
  push:
    branches: electron

jobs:
  build:
    runs-on: windows-latest
    steps:
    - run: mkdir -p ~/.ssh
    - run: echo -n "$SSH_TOKEN" | %{[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($_))} >$HOME/.ssh/id_rsa
      env:
          SSH_TOKEN: ${{ secrets.PARSEGRAPH_SSH_TOKEN }}
    - run: chmod 0400 $HOME/.ssh/id_rsa
    - run: "$SSH_TOKEN_SHA1SUM" -eq (Get-FileHash -Algorithm SHA1 $HOME/.ssh/id_rsa) || throw "sha1sum not equal"
      env:
          SSH_TOKEN_SHA1SUM: ${{ secrets.PARSEGRAPH_SSH_TOKEN_SHA1SUM }}
    - run: echo -n "$SSH_KNOWN_HOST" | %{[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($_))} >$HOME/.ssh/known_hosts
      env:
          SSH_KNOWN_HOST: ${{ secrets.PARSEGRAPH_SSH_KNOWN_HOST }}

    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 20
        registry-url: 'https://registry.npmjs.org'
    - run: cd occluder && yarn && ./deploy.sh && cd ..
    - run: yarn
    - run: yarn build
    - run: cd build && sed -i -re 's/React App/parsegraph/g' ./index.html
    - run: cd electron && yarn && ./build.sh


    - run: export VERSION=`node -e 'console.log(JSON.parse(require("fs").readFileSync("electron/package.json")).version)'` && ssh $SSH_HOST "mkdir -p $PARSEGRAPH_PUBLIC_HTML/electron/$VERSION"
      env:
          PARSEGRAPH_PUBLIC_HTML: ${{ secrets.PARSEGRAPH_PUBLIC_HTML }}
          SSH_HOST: ${{ secrets.PARSEGRAPH_SSH_HOST }}
    - run: export VERSION=`node -e 'console.log(JSON.parse(require("fs").readFileSync("electron/package.json")).version)'` && cd electron/out/make && scp -r * "$SSH_HOST:$PARSEGRAPH_PUBLIC_HTML/electron/$VERSION/" && ssh $SSH_HOST "cd $PARSEGRAPH_PUBLIC_HTML/electron; rm -f latest; ln -s $VERSION latest"
      env:
          PARSEGRAPH_PUBLIC_HTML: ${{ secrets.PARSEGRAPH_PUBLIC_HTML }}
          SSH_HOST: ${{ secrets.PARSEGRAPH_SSH_HOST }}
